### ISSUE TITLE
Pip install command returns an installation error

### ISSUE THREAD

**Issue by mannyanebi** [kjaymiller/render_engine_theme_kjaymiller#33]
So, when I run `pip install kjaymiller-render-engine-theme`

I get the following error statements returned

```
ERROR: Could not find a version that satisfies the requirement kjaymiller-render-engine-theme (from versions: none)
ERROR: No matching distribution found for kjaymiller-render-engine-theme
```

**Comment by kjaymiller** [comment]
The python module is `render-engine-theme-kjaymiller` creating an issue to correct that and some of the information int eh pyproject.toml

**Comment by mannyanebi** [comment]
Hi, @kjaymiller. I'm trying to push to some branches with code that fixes this issue and #35 
I'm getting a 403 - unauthorized. What could be wrong?

**Comment by kjaymiller** [comment]
If you're trying to push directly to my repo then it would not let you. If you forked the repo to your own branch you can then submit a pull request.

**Comment by mannyanebi** [comment]
Okay. That makes sense. Thanks so much
