### ISSUE TITLE
Update README and paths for pyproject.toml

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/render_engine_theme_kjaymiller#34]
The readme has instructions for the wrong pypi path. it should be 

`pip install render-engine-theme-kjaymiller`

I noticed in trying to find the module in PyPI that the information is still listed as example code and other things.

_Originally posted by @kjaymiller in https://github.com/kjaymiller/render_engine_theme_kjaymiller/issues/33#issuecomment-1757655183_

**Comment by mannyanebi** [comment]
When you say "relative paths for `pyproject.toml`", what should I look for to fix, so that the module information in pypi gets updated?

**Comment by kjaymiller** [comment]
disregard the pyproject.toml issue. That was a bug in publishing (it published a zero version which didn't have any information assigned to it). 

It will be corrected when the next stable release is out.

**The README still needs to be updated**

**Comment by mannyanebi** [comment]
Got it. I think this PR #39 fixes this issue
